# Generated by Django 5.2.17 on 2026-09-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_savedfilter_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contacts.category'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='companies', to='contacts.tag'),
        ),
        migrations.AddField(
            model_name='person',
            name='favourite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
