# Generated by Django 5.2.17 on 2026-09-06 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_company_categories_company_tags_person_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('lt', 'Lietuvių'), ('en', 'English')], default='lt', max_length=5)),
                ('timezone', models.CharField(default='Europe/Vilnius', max_length=64)),
                ('avatar', models.FileField(blank=True, upload_to='avatars/%Y/%m/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
