# Generated by Django 5.2.17 on 2026-09-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('tag-color-0', 'Mėlyna'), ('tag-color-1', 'Pilka'), ('tag-color-2', 'Žalia'), ('tag-color-3', 'Violetinė'), ('tag-color-4', 'Oranžinė'), ('tag-color-5', 'Žydra'), ('tag-color-6', 'Raudona'), ('tag-color-7', 'Auksinė')], max_length=20),
        ),
    ]
