# Generated by Django 5.2.17 on 2026-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('level', models.CharField(choices=[('strict', 'Griežtas'), ('standard', 'Standartinis'), ('loose', 'Laisvas')], default='standard', max_length=12)),
                ('check_on_edit', models.BooleanField(default=True)),
                ('check_on_import', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
