# Generated by Django 5.2.17 on 2026-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_company_merged_into_person_merged_into'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedfilter',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
