# Generated by Django 5.2.17 on 2026-09-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_savedfilter_options_savedfilter_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('person', 'Kontaktai'), ('company', 'Įmonės')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Trumpas tekstas'), ('textarea', 'Ilgas tekstas'), ('bool', 'Žymimasis langelis'), ('select', 'Vienas pasirinkimas'), ('multiselect', 'Keli pasirinkimai')], default='text', max_length=12)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'name'), name='unique_custom_field_name_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='CustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='contacts.company')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='contacts.customfield')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='contacts.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('field', 'person'), name='unique_custom_value_person'), models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('field', 'company'), name='unique_custom_value_company')],
            },
        ),
    ]
