# Generated by Django 5.2.17 on 2026-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_company_owner_person_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administratorius'), ('member', 'Naudotojas (visi įrašai)'), ('restricted', 'Naudotojas (tik savi įrašai)')], default='member', max_length=12),
        ),
    ]
