# Generated by Django 5.2.17 on 2026-09-08 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('create', 'Sukūrimas'), ('update', 'Keitimas'), ('archive', 'Archyvavimas'), ('restore', 'Atkūrimas'), ('delete', 'Trynimas'), ('merge', 'Sujungimas'), ('import', 'Importas'), ('export', 'Eksportas'), ('setting', 'Nustatymų keitimas'), ('login', 'Prisijungimas'), ('logout', 'Atsijungimas'), ('login_failed', 'Nepavykęs prisijungimas')], db_index=True, max_length=16)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=32)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('field', models.CharField(blank=True, max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Žurnalo įrašas',
                'verbose_name_plural': 'Žurnalas',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
