# Generated by Django 5.2.17 on 2026-09-08 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='responsible_for_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='responsible_for_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
