# Generated by Django 5.2.17 on 2026-09-08 08:35

from django.db import migrations, models


def seed_visibility_from_role(apps, schema_editor):
    UserProfile = apps.get_model('contacts', 'UserProfile')
    UserProfile.objects.filter(role='restricted').update(record_visibility='own')


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='record_visibility',
            field=models.CharField(choices=[('all', 'Visi įrašai'), ('team', 'Tik komandos įrašai'), ('own', 'Tik savo įrašai')], default='all', max_length=8),
        ),
        migrations.RunPython(seed_visibility_from_role, migrations.RunPython.noop),
    ]
