# Generated by Django 5.2.17 on 2026-09-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_userprofile_record_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=12, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
