# Generated by Django 5.2.17 on 2026-09-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_rolepermissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='company',
            name='cooperation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_note',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Žemas'), ('medium', 'Vidutinis'), ('high', 'Aukštas')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='cooperation_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='person',
            name='internal_note',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='person',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Žemas'), ('medium', 'Vidutinis'), ('high', 'Aukštas')], default='', max_length=8),
        ),
    ]
