# Generated by Django 5.2.17 on 2026-09-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_company_contact_type_company_cooperation_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cooperation_start',
        ),
        migrations.RemoveField(
            model_name='company',
            name='internal_note',
        ),
        migrations.RemoveField(
            model_name='company',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='person',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cooperation_start',
        ),
        migrations.RemoveField(
            model_name='person',
            name='internal_note',
        ),
        migrations.RemoveField(
            model_name='person',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
