# Generated by Django 5.2.17 on 2026-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_drop_unused_priority_and_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_page_size', models.PositiveSmallIntegerField(choices=[(25, '25'), (50, '50'), (100, '100')], default=50)),
                ('date_format', models.CharField(choices=[('Y-m-d', '2026-12-31'), ('d.m.Y', '31.12.2026'), ('m/d/Y', '12/31/2026')], default='Y-m-d', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
