# Generated by Django 5.2.17 on 2026-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='import_delimiter',
            field=models.CharField(choices=[('auto', 'Automatiškai'), (',', 'Kablelis ( , )'), (';', 'Kabliataškis ( ; )'), ('tab', 'Tabuliacija')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='import_encoding',
            field=models.CharField(choices=[('auto', 'Automatiškai'), ('utf-8-sig', 'UTF-8'), ('cp1257', 'Windows-1257 (Baltijos)')], default='auto', max_length=16),
        ),
    ]
