# Generated by Django 5.2.17 on 2026-09-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_systemsettings_import_delimiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contacts.person'),
        ),
    ]
