# Generated by Django 5.2.17 on 2026-09-08 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_assignee(apps, schema_editor):
    Reminder = apps.get_model("contacts", "Reminder")
    Reminder.objects.filter(assigned_to__isnull=True).update(assigned_to=models.F("created_by"))


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_reminder_company_reminder_end_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_assigned_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(choices=[('low', 'Žemas'), ('normal', 'Įprastas'), ('high', 'Aukštas')], default='normal', max_length=8),
        ),
        migrations.RunPython(backfill_assignee, migrations.RunPython.noop),
    ]
