# Generated by Django 5.2.17 on 2026-09-08 20:36

import datetime
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


def unique_tokens(apps, schema_editor):
    UserProfile = apps.get_model("contacts", "UserProfile")
    for profile in UserProfile.objects.all().iterator():
        profile.unsubscribe_token = secrets.token_urlsafe(24)
        profile.save(update_fields=["unsubscribe_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_sanitize_stored_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='assigned_notified_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='upcoming_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='digest_default_time',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notify_default_lead',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Išjungta'), (15, '15 min.'), (60, '1 val.'), (1440, '1 diena')], default=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_lead',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Išjungta'), (15, '15 min.'), (60, '1 val.'), (1440, '1 diena')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unsubscribe_token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=48, unique=True),
        ),
        migrations.RunPython(unique_tokens, migrations.RunPython.noop),
    ]
