# Generated by Django 5.2.17 on 2026-09-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_reminder_assigned_notified_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recurrence_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_freq',
            field=models.CharField(blank=True, choices=[('', 'Nekartoti'), ('daily', 'Kasdien'), ('weekly', 'Kas savaitę'), ('monthly', 'Kas mėnesį'), ('yearly', 'Kasmet')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_children', to='contacts.reminder'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
