# Generated by Django 5.2.17 on 2026-09-08 21:04

import secrets
from django.db import migrations, models


def unique_tokens(apps, schema_editor):
    UserProfile = apps.get_model("contacts", "UserProfile")
    for profile in UserProfile.objects.all().iterator():
        profile.calendar_token = secrets.token_urlsafe(24)
        profile.save(update_fields=["calendar_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_reminder_recurrence_count_reminder_recurrence_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=48, unique=True),
        ),
        migrations.RunPython(unique_tokens, migrations.RunPython.noop),
    ]
