# Generated by Django 5.2.17 on 2026-09-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_userprofile_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_addr', models.CharField(max_length=320)),
                ('to_addrs', models.CharField(blank=True, max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.activity')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
