# Generated by Django 5.2.17 on 2026-09-09 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_systemsettings_integration_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='automations_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('contact_no_owner_after', 'Kontaktas be atsakingo ilgiau nei N dienų'), ('contact_silent_days', 'Su kontaktu (turinčiu atsakingą) nebendrauta N dienų'), ('contact_never_contacted_after', 'Su nauju kontaktu nebendrauta N dienų'), ('reminder_overdue_days', 'Priminimas vėluoja N dienų')], max_length=32)),
                ('threshold', models.PositiveIntegerField(default=1, help_text='Dienų skaičius (N).')),
                ('action', models.CharField(choices=[('notify_user', 'Pranešti naudotojui el. paštu'), ('assign_owner', 'Priskirti atsakingą'), ('create_task', 'Sukurti užduotį'), ('add_tag', 'Pridėti žymą')], max_length=16)),
                ('action_text', models.CharField(blank=True, default='', max_length=200)),
                ('action_due_days', models.PositiveIntegerField(default=3)),
                ('active', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.tag')),
                ('action_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=16)),
                ('target_id', models.CharField(db_index=True, max_length=32)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='ok', max_length=8)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.automationrule')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
