# Generated by Django 5.2.17 on 2026-09-09 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_webhooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='target_url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
