# Generated by Django 5.2.17 on 2026-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_webhook_url_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
