# Generated by Django 5.2.17 on 2026-09-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0037_translation_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatesettings',
            name='level',
        ),
        migrations.CreateModel(
            name='DuplicateException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Kontaktas'), ('company', 'Įmonė')], max_length=8)),
                ('left_id', models.PositiveIntegerField()),
                ('right_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'left_id', 'right_id'), name='unique_duplicate_exception')],
            },
        ),
    ]
