# Generated by Django 5.2.17 on 2026-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0038_drop_dup_level_add_dup_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='notify_default_lead',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notify_lead',
        ),
        migrations.AddField(
            model_name='reminder',
            name='notify_before',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nesiųsti'), (15, '15 min.'), (60, '1 val.'), (1440, '1 diena')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='digest_skip_weekends',
            field=models.BooleanField(default=False),
        ),
    ]
