# Generated by Django 5.2.17 on 2026-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_notifications_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='menu_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
