# Generated by Django 5.2.17 on 2026-09-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_user_menu_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_authorization_endpoint',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_groups_claim',
            field=models.CharField(blank=True, default='groups', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_issuer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_jwks_endpoint',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_provider',
            field=models.CharField(choices=[('entra', 'Microsoft Entra ID'), ('generic', 'AD FS / OpenID Connect')], default='entra', max_length=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_sync_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_token_endpoint',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_userinfo_endpoint',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='directory_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='directory_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='directory_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='directory_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DirectoryGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=256, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administratorius'), ('member', 'Naudotojas (visi įrašai)'), ('restricted', 'Naudotojas (tik savi įrašai)')], default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory_groups', to='contacts.team')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
    ]
