# Generated by Django 5.2.17 on 2026-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0041_directory_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='oidc_session_check_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sso_only',
            field=models.BooleanField(default=False),
        ),
    ]
