# Generated by Django 5.2.17 on 2026-09-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0042_sso_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorygroupmapping',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administratorius'), ('member', 'Naudotojas (visi įrašai)'), ('restricted', 'Naudotojas (tik savi įrašai)'), ('readonly', 'Skaitytojas (tik peržiūra)')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administratorius'), ('member', 'Naudotojas (visi įrašai)'), ('restricted', 'Naudotojas (tik savi įrašai)'), ('readonly', 'Skaitytojas (tik peržiūra)')], default='member', max_length=12),
        ),
    ]
