# Generated by Django 5.2.17 on 2026-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0043_readonly_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='deactivate_inactive_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_reason',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
