# Generated by Django 5.2.17 on 2026-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0044_inactive_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='rate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='rate_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
