# Generated by Django 5.2.17 on 2026-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0045_api_token_expiry_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
