# Generated by Django 5.2.17 on 2026-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0048_audit_redaction_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='archived_retention_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='incoming_mail_retention_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
