# Generated by Django 5.2.17 on 2026-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0052_translation_msgid_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='calendar_feed_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
