# Generated by Django 5.2.17 on 2026-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0053_calendar_feed_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="reminder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("call", "Skambutis"),
                    ("meeting", "Susitikimas"),
                    ("reminder", "Priminimas"),
                ],
                db_index=True,
                default="reminder",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="meeting_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="notify_before",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Nesiųsti"),
                    (5, "5 min."),
                    (15, "15 min."),
                    (60, "1 val."),
                    (1440, "1 diena"),
                    (2880, "2 dienos"),
                ],
                null=True,
            ),
        ),
    ]
