# Generated by Django 5.2.17 on 2026-09-19 20:36

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0054_event_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="personal_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=11,
                validators=[contacts.validators.validate_personal_code],
            ),
        ),
    ]
