# Generated by Django 5.2.17 on 2026-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0055_reporting_reminder_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorygroupmapping",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administratorius"),
                    ("manager", "Vadovas (visi įrašai)"),
                    ("member", "Naudotojas (visi įrašai)"),
                    ("restricted", "Naudotojas (tik savi įrašai)"),
                    ("readonly", "Skaitytojas (tik peržiūra)"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administratorius"),
                    ("manager", "Vadovas (visi įrašai)"),
                    ("member", "Naudotojas (visi įrašai)"),
                    ("restricted", "Naudotojas (tik savi įrašai)"),
                    ("readonly", "Skaitytojas (tik peržiūra)"),
                ],
                default="member",
                max_length=12,
            ),
        ),
    ]
