# Generated by Django 5.2.17 on 2026-09-24 06:51

import django.db.models.functions.text
from django.conf import settings
import re

from django.db import migrations, models


def fill_digits(apps, schema_editor):
    """Existing phones get the digits the duplicate check now looks them up by."""
    for model, source, target in (("PhoneNumber", "number", "digits"), ("Company", "phone", "phone_digits")):
        Model = apps.get_model("contacts", model)
        batch = []
        for row in Model.objects.exclude(**{source: ""}).only("pk", source).iterator(chunk_size=2000):
            setattr(row, target, re.sub(r"\D", "", getattr(row, source)))
            batch.append(row)
            if len(batch) == 2000:
                Model.objects.bulk_update(batch, [target])
                batch = []
        Model.objects.bulk_update(batch, [target])


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0056_alter_directorygroupmapping_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("person", "Kontaktas"), ("company", "Įmonė")],
                        max_length=8,
                    ),
                ),
                ("left_id", models.PositiveIntegerField()),
                ("right_id", models.PositiveIntegerField(db_index=True)),
                ("reasons", models.CharField(max_length=80)),
                ("found_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="phone_digits",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="digits",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("name")
                ),
                name="company_name_key",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("email")
                ),
                name="company_email_key",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("vat_code")
                ),
                name="company_vat_key",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("company_code")
                ),
                name="company_code_key",
            ),
        ),
        migrations.AddIndex(
            model_name="emailaddress",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("email")
                ),
                name="email_key",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("last_name")
                ),
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("first_name")
                ),
                name="person_name_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=("kind", "left_id", "right_id"),
                name="unique_duplicate_candidate",
            ),
        ),
        migrations.RunPython(fill_digits, migrations.RunPython.noop),
    ]
