# Generated by Django 5.2.17 on 2026-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0058_search_trigram_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField()),
            ],
        ),
    ]
