# Generated by Django 5.2.17 on 2026-09-24 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0059_analytics_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="external_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="person",
            name="personal_code_encrypted",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AddField(
            model_name="person",
            name="personal_code_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="personal_code_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lt", "Lietuvos asmens kodas"),
                    ("other", "Kitas identifikatorius"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Sukūrimas"),
                    ("update", "Keitimas"),
                    ("archive", "Archyvavimas"),
                    ("restore", "Atkūrimas"),
                    ("delete", "Trynimas"),
                    ("merge", "Sujungimas"),
                    ("import", "Importas"),
                    ("export", "Eksportas"),
                    ("setting", "Nustatymų keitimas"),
                    ("login", "Prisijungimas"),
                    ("logout", "Atsijungimas"),
                    ("login_failed", "Nepavykęs prisijungimas"),
                    ("view", "Peržiūra"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id", "external_source"),
                name="unique_person_external_id",
            ),
        ),
    ]
