# Generated by Django 5.2.17 on 2026-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0060_person_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
