# Generated by Django 5.2.17 on 2026-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0060_reporting_reminder_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissions",
            name="blocks",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
