# Generated by Django 5.2.17 on 2026-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0061_rolepermissions_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Sukūrimas"),
                    ("update", "Keitimas"),
                    ("archive", "Archyvavimas"),
                    ("restore", "Atkūrimas"),
                    ("delete", "Trynimas"),
                    ("merge", "Sujungimas"),
                    ("import", "Importas"),
                    ("export", "Eksportas"),
                    ("setting", "Nustatymų keitimas"),
                    ("login", "Prisijungimas"),
                    ("logout", "Atsijungimas"),
                    ("login_failed", "Nepavykęs prisijungimas"),
                    ("access", "Prieiga prie įrašo"),
                    ("personal_code", "Asmens kodo peržiūra"),
                    ("search_miss", "Paieška be rezultato"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
