#!/bin/sh
# Set up the Regitra staging instance on the NAS. Run once, on the NAS itself.
#
#   sh scripts/setup-regitra-staging.sh <tailnet-domain> [app-dir]
#
# e.g. sh scripts/setup-regitra-staging.sh tailb8493f.ts.net
#
# It makes the directory and writes its .env with freshly generated secrets.
# It never touches an existing .env, and never copies keys from another
# instance — two tiers sharing a key is two tiers that can read each other.
#
# What it cannot do for you: the Tailscale auth key (paste it when asked, or
# put it in TS_AUTHKEY), and the two GitHub repository variables it prints at
# the end. See docs/REGITRA-STAGING.md.
set -eu

TAILNET="${1:-}"
APP="${2:-/opt/crm-regitra-staging}"
HOSTNAME_="crm-regitra-staging"

[ -n "$TAILNET" ] || { echo "usage: sh scripts/setup-regitra-staging.sh <tailnet-domain> [app-dir]"; exit 2; }
DOMAIN="${HOSTNAME_}.${TAILNET}"

# On the NAS runner the app directory is a bind mount from the host. Without it
# this would write into the container and vanish with the job, so say so plainly
# instead of appearing to succeed.
if [ -n "${GITHUB_ACTIONS:-}" ] && ! mountpoint -q "$APP" 2>/dev/null; then
  echo "FATAL: $APP is not mounted into the runner."
  echo
  echo "Add this line to the crm-runner project's compose.yaml on the NAS,"
  echo "under 'volumes:', and recreate the project:"
  echo
  echo "      - ${APP}:${APP}"
  echo
  echo "See deploy/runner/README.md and docs/REGITRA-STAGING.md."
  exit 1
fi

if [ -e "$APP/.env" ]; then
  echo "FATAL: $APP/.env already exists — refusing to overwrite it."
  echo "       Delete it by hand if you really mean to start over."
  exit 1
fi

# --- secrets, generated here and never shown twice -----------------------
# A Fernet key is url-safe base64 of 32 random bytes, which is what this is.
secret_key="$(openssl rand -base64 64 | tr -d '\n' | tr '+/' '-_')"
fernet_key="$(openssl rand -base64 32 | tr '+/' '-_')"
db_password="$(openssl rand -base64 30 | tr -d '\n' | tr '+/' '-_')"

# Asked for at a terminal; passed in as TS_AUTHKEY when this runs as a job.
if [ -z "${TS_AUTHKEY:-}" ] && [ -t 0 ]; then
  printf 'Tailscale auth key (tskey-auth-...), or Enter to fill it in later: '
  read -r TS_AUTHKEY || TS_AUTHKEY=""
fi
TS_AUTHKEY="${TS_AUTHKEY:-}"

mkdir -p "$APP"
umask 077
cat > "$APP/.env" <<ENV
# Regitra staging. Generated by scripts/setup-regitra-staging.sh.
# An isolated copy of production data running the regitra branch.
COMPOSE_FILE=compose.yaml:compose.tailscale.yaml:compose.staging.yaml:compose.regitra-staging.yaml
COMPOSE_PROJECT_NAME=crm-regitra-staging
CRM_FLAVOUR=regitra
CRM_ENVIRONMENT=staging

TS_AUTHKEY=${TS_AUTHKEY}
TS_HOSTNAME=${HOSTNAME_}
TS_CERT_DOMAIN=${DOMAIN}
# Not serve.json: that one enables Funnel, which would publish a copy of
# production data to the public internet.
TS_SERVE_CONFIG=/config/serve-staging.json

CRM_DOMAIN=${DOMAIN}
DJANGO_ALLOWED_HOSTS=${DOMAIN}
DJANGO_CSRF_TRUSTED_ORIGINS=https://${DOMAIN}
CRM_BASE_URL=https://${DOMAIN}

# Different from the public staging's — host ports are all the two stacks share.
CRM_PORT=8082
CRM_LAN_PORT=18083

DJANGO_SECRET_KEY=${secret_key}
CRM_SECRETS_KEY=${fernet_key}
POSTGRES_PASSWORD=${db_password}
ENV
chmod 600 "$APP/.env"

echo "Wrote $APP/.env (secrets generated, mode 600)."
[ -n "$TS_AUTHKEY" ] || echo "NOTE: TS_AUTHKEY is empty — fill it in before the first start."
cat <<NEXT

Two repository variables still to set, in GitHub →
Settings → Secrets and variables → Actions → Variables:

  CRM_REGITRA_STAGING_DIR  ${APP}
  CRM_REGITRA_STAGING_URL  https://${DOMAIN}

And an environment named "Regitra staging" under Settings → Environments.

Then push to the regitra branch, or run the "Deploy Regitra staging" workflow
by hand. To bring it up locally instead:

  cd ${APP} && docker compose build --pull && docker compose up -d
NEXT
